#include <stdio.h>
typedef int qboolean;
#include "s3eKeyboard.h"
#include "keys.h"

const int mmkeymap[256] = {
        [s3eKey0] = '0',
        [s3eKey1] = '1',
        [s3eKey2] = '2',
        [s3eKey3] = '3',
        [s3eKey4] = '4',
        [s3eKey5] = '5',
        [s3eKey6] = '6',
        [s3eKey7] = '7',
        [s3eKey8] = '8',
        [s3eKey9] = '9',
        [s3eKeyA] = 'A',
        [s3eKeyB] = 'B',
        [s3eKeyBackspace] = K_BACKSPACE,
        [s3eKeyC] = 'C',
        [s3eKeyD] = 'D',
        [s3eKeyDelete] = K_DEL,
        [s3eKeyDown] = K_DOWNARROW,
        [s3eKeyE] = 'E',
        [s3eKeyEnter] = K_ENTER,
        [s3eKeyEsc] = K_ESCAPE,
        [s3eKeyF] = 'F',
        [s3eKeyF1] = K_F1,
        [s3eKeyF10] = K_F10,
        [s3eKeyF11] = K_F11,
        [s3eKeyF12] = K_F12,
        [s3eKeyF2] = K_F2,
        [s3eKeyF3] = K_F3,
        [s3eKeyF4] = K_F4,
        [s3eKeyF5] = K_F5,
        [s3eKeyF6] = K_F6,
        [s3eKeyF7] = K_F7,
        [s3eKeyF8] = K_F8,
        [s3eKeyF9] = K_F9,
        [s3eKeyG] = 'G',
        [s3eKeyH] = 'H',
        [s3eKeyHome] = K_HOME,
        [s3eKeyI] = 'I',
        [s3eKeyInsert] = K_INS,
        [s3eKeyJ] = 'J',
        [s3eKeyK] = 'K',
        [s3eKeyKbEnd] = K_END,
        [s3eKeyL] = 'L',
        [s3eKeyLeft] = K_LEFTARROW,
        [s3eKeyLeftAlt] = K_ALT,
        [s3eKeyLeftControl] = K_CTRL,
        [s3eKeyLeftShift] = K_SHIFT,
        [s3eKeyM] = 'M',
        [s3eKeyN] = 'N',
        [s3eKeyO] = 'O',
        [s3eKeyP] = 'P',
        [s3eKeyPageDown] = K_PGDN,
        [s3eKeyPageUp] = K_PGUP,
        [s3eKeyPause] = K_PAUSE,
        [s3eKeyQ] = 'Q',
        [s3eKeyR] = 'R',
        [s3eKeyRight] = K_RIGHTARROW,
        [s3eKeyS] = 'S',
        [s3eKeySpace] = K_SPACE,
        [s3eKeyT] = 'T',
        [s3eKeyTab] = K_TAB,
        [s3eKeyU] = 'U',
        [s3eKeyUp] = K_UPARROW,
        [s3eKeyV] = 'V',
        [s3eKeyW] = 'W',
        [s3eKeyX] = 'X',
        [s3eKeyY] = 'Y',
        [s3eKeyZ] = 'Z'
};

